authors:
  billz:
    name: Bill Zimmerman
    description: Creator
    avatar: /blog/assets/images/billz.jpeg
    url: https://github.com/billz
  ruralmeltdown:
    name: RuralMeltdown
    description: Creator
    avatar: /blog/assets/images/ruralmeltdown.jpg
    url: https://github.com/ruralmeltdown